In [ ]:
#Importação das bibliotecas.
import pandas as pd 

df = pd.read_csv("Copa-do-Mundo-da-FIFA-2026.csv", index_col= False, sep= ";")
df

             Equipes  Pts  PJ  VIT  E  DER  GM  GC  SG
0             México    9   3    3  0    0   6   0   6
1      África do Sul    4   3    1  1    1   2   3  -1
2      Coreia do Sul    3   3    1  0    2   2   3  -1
3   República Tcheca    1   3    0  1    2   2   6  -4
4              Suíça    7   3    2  1    0   7   3   4
5             Canadá    4   3    1  1    1   8   3   5
6             Bósnia    4   3    1  1    1   5   6  -1
7              Catar    1   3    0  1    2   2  10  -8
8             Brasil    7   3    2  1    0   7   1   6
9           Marrocos    7   3    2  1    0   6   3   3
10           Escócia    3   3    1  0    2   1   4  -3
11             Haiti    0   3    0  0    3   2   8  -6
12    Estados Unidos    6   3    2  0    1   8   4   4
13         Austrália    4   3    1  1    1   2   2   0
14          Paraguai    4   3    1  1    1   2   4  -2
15           Turquia    3   3    1  0    2   3   5  -2
16          Alemanha    6   3    2  0    1  10   4   6
17   Costa do Marfim    6   3    2  0    1   4   2   2
18           Equador    4   3    1  1    1   2   2   0
19           Curacao    1   3    0  1    2   1   9  -8
20           Holanda    7   3    2  1    0  10   4   6
21             Japão    5   3    1  2    0   7   3   4
22            Suécia    4   3    1  1    1   7   7   0
23           Tunísia    0   3    0  0    3   2  12 -10
24           Bélgica    5   3    1  2    0   6   2   4
25             Egito    5   3    1  2    0   5   3   2
26               Irã    3   3    0  3    0   3   3   0
27     Nova Zelândia    1   3    0  1    2   4  10  -6
28           Espanha    7   3    2  1    0   5   0   5
29        Cabo Verde    3   3    0  3    0   2   2   0
30           Uruguai    2   3    0  2    1   3   4  -1
31    Arábia Saudita    2   3    0  2    1   1   5  -4
32            França    9   3    3  0    0  10   2   8
33           Noruega    6   3    2  0    1   8   7   1
34           Senegal    3   3    1  0    2   8   6   2
35            Iraque    0   3    0  0    3   1  12 -11
36         Argentina    9   3    3  0    0   8   1   7
37           Áustria    4   3    1  1    1   6   6   0
38           Argélia    4   3    1  1    1   5   7   0
39          Jordânia    0   3    0  0    3   3   8  -5
40          Colômbia    7   3    2  1    0   4   1   3
41          Portugal    5   3    1  2    0   6   1   5
42          RD Congo    4   3    1  1    1   4   3   1
43       Uzbequistão    0   3    0  0    3   2  11  -9
44        Inglaterra    7   3    2  1    0   6   2   4
45           Croácia    6   3    2  0    1   5   5   0
46              Gana    4   3    1  1    1   2   2   0
47            Panamá    0   3    0  0    3   0   4  -4

In [ ]:
print("1. Desempenho das equipes")

1. Desempenho das equipes

In [ ]:
print("Qual seleção fez mais pontos?")
df.nlargest(1, "Pts")[["Equipes", "Pts"]].style.hide(axis="index")

Qual seleção fez mais pontos?

In [ ]:
print("Quais seleções terminaram invictas?")
df[df["DER"] == 0][["Equipes", "PJ", "VIT", "E", "DER"]].style.hide(axis="index")

Quais seleções terminaram invictas?

In [ ]:
print("Quais tiveram o pior desempenho?")
df.nsmallest(10, "Pts")[["Equipes", "Pts"]].style.hide(axis="index")

Quais tiveram o pior desempenho?

In [ ]:
print("Quem venceu mais partidas?")
df.nlargest(10, "VIT")[["Equipes", "VIT"]].style.hide(axis="index")

Quem venceu mais partidas?

In [ ]:
print("Quem perdeu mais partidas?")
df.nlargest(10, "DER")[["Equipes", "DER"]].style.hide(axis="index")

Quem perdeu mais partidas?

In [ ]:
print("2. Ataque e defesa")

2. Ataque e defesa

In [ ]:
print("Melhor ataque")
df.nlargest(10, "GM")[["Equipes", "GM"]].style.hide(axis="index")

Melhor ataque

In [ ]:
print("Melhor defesa")
df.nsmallest(10, "GC")[["Equipes", "GC"]].style.hide(axis="index")

Melhor defesa

In [ ]:
print("Existe relação entre gols marcados e pontos?")
df[["GM", "Pts"]].corr().style.hide(axis="index")
#Se o valor estiver próximo de 1, existe uma forte relação positiva.

Existe relação entre gols marcados e pontos?

In [ ]:
print("Melhor saldo de gols")
df.nlargest(10, "SG")[["Equipes", "SG"]].style.hide(axis="index")

Melhor saldo de gols

In [ ]:
print("3. Eficiência")

3. Eficiência

In [ ]:
df["Aproveitamento (%)"] = (df["Pts"] / (df["PJ"] * 3)) * 100

df["GM/Jogo"] = df["GM"] / df["PJ"]

df["GC/Jogo"] = df["GC"] / df["PJ"]

df["Pts/Jogo"] = df["Pts"] / df["PJ"]

df["SG/Jogo"] = df["SG"] / df["PJ"]

df

,Equipes,Pts,PJ,VIT,E,DER,GM,GC,SG,Aproveitamento (%),GM/Jogo,GC/Jogo,Pts/Jogo,SG/Jogo
0,México,9,3,3,0,0,6,0,6,100.000000,2.000000,0.000000,3.000000,2.000000
1,África do Sul,4,3,1,1,1,2,3,-1,44.444444,0.666667,1.000000,1.333333,-0.333333
2,Coreia do Sul,3,3,1,0,2,2,3,-1,33.333333,0.666667,1.000000,1.000000,-0.333333
3,República Tcheca,1,3,0,1,2,2,6,-4,11.111111,0.666667,2.000000,0.333333,-1.333333
4,Suíça,7,3,2,1,0,7,3,4,77.777778,2.333333,1.000000,2.333333,1.333333
5,Canadá,4,3,1,1,1,8,3,5,44.444444,2.666667,1.000000,1.333333,1.666667
6,Bósnia,4,3,1,1,1,5,6,-1,44.444444,1.666667,2.000000,1.333333,-0.333333
7,Catar,1,3,0,1,2,2,10,-8,11.111111,0.666667,3.333333,0.333333,-2.666667
8,Brasil,7,3,2,1,0,7,1,6,77.777778,2.333333,0.333333,2.333333,2.000000
9,Marrocos,7,3,2,1,0,6,3,3,77.777778,2.000000,1.000000,2.333333,1.000000
10,Escócia,3,3,1,0,2,1,4,-3,33.333333,0.333333,1.333333,1.000000,-1.000000
11,Haiti,0,3,0,0,3,2,8,-6,0.000000,0.666667,2.666667,0.000000,-2.000000
12,Estados Unidos,6,3,2,0,1,8,4,4,66.666667,2.666667,1.333333,2.000000,1.333333
13,Austrália,4,3,1,1,1,2,2,0,44.444444,0.666667,0.666667,1.333333,0.000000
14,Paraguai,4,3,1,1,1,2,4,-2,44.444444,0.666667,1.333333,1.333333,-0.666667
15,Turquia,3,3,1,0,2,3,5,-2,33.333333,1.000000,1.666667,1.000000,-0.666667
16,Alemanha,6,3,2,0,1,10,4,6,66.666667,3.333333,1.333333,2.000000,2.000000
17,Costa do Marfim,6,3,2,0,1,4,2,2,66.666667,1.333333,0.666667,2.000000,0.666667
18,Equador,4,3,1,1,1,2,2,0,44.444444,0.666667,0.666667,1.333333,0.000000
19,Curacao,1,3,0,1,2,1,9,-8,11.111111,0.333333,3.000000,0.333333,-2.666667
20,Holanda,7,3,2,1,0,10,4,6,77.777778,3.333333,1.333333,2.333333,2.000000
21,Japão,5,3,1,2,0,7,3,4,55.555556,2.333333,1.000000,1.666667,1.333333
22,Suécia,4,3,1,1,1,7,7,0,44.444444,2.333333,2.333333,1.333333,0.000000
23,Tunísia,0,3,0,0,3,2,12,-10,0.000000,0.666667,4.000000,0.000000,-3.333333
24,Bélgica,5,3,1,2,0,6,2,4,55.555556,2.000000,0.666667,1.666667,1.333333
25,Egito,5,3,1,2,0,5,3,2,55.555556,1.666667,1.000000,1.666667,0.666667
26,Irã,3,3,0,3,0,3,3,0,33.333333,1.000000,1.000000,1.000000,0.000000
27,Nova Zelândia,1,3,0,1,2,4,10,-6,11.111111,1.333333,3.333333,0.333333,-2.000000
28,Espanha,7,3,2,1,0,5,0,5,77.777778,1.666667,0.000000,2.333333,1.666667
29,Cabo Verde,3,3,0,3,0,2,2,0,33.333333,0.666667,0.666667,1.000000,0.000000
30,Uruguai,2,3,0,2,1,3,4,-1,22.222222,1.000000,1.333333,0.666667,-0.333333
31,Arábia Saudita,2,3,0,2,1,1,5,-4,22.222222,0.333333,1.666667,0.666667,-1.333333
32,França,9,3,3,0,0,10,2,8,100.000000,3.333333,0.666667,3.000000,2.666667
33,Noruega,6,3,2,0,1,8,7,1,66.666667,2.666667,2.333333,2.000000,0.333333
34,Senegal,3,3,1,0,2,8,6,2,33.333333,2.666667,2.000000,1.000000,0.666667
35,Iraque,0,3,0,0,3,1,12,-11,0.000000,0.333333,4.000000,0.000000,-3.666667
36,Argentina,9,3,3,0,0,8,1,7,100.000000,2.666667,0.333333,3.000000,2.333333
37,Áustria,4,3,1,1,1,6,6,0,44.444444,2.000000,2.000000,1.333333,0.000000
38,Argélia,4,3,1,1,1,5,7,0,44.444444,1.666667,2.333333,1.333333,0.000000
39,Jordânia,0,3,0,0,3,3,8,-5,0.000000,1.000000,2.666667,0.000000,-1.666667
40,Colômbia,7,3,2,1,0,4,1,3,77.777778,1.333333,0.333333,2.333333,1.000000
41,Portugal,5,3,1,2,0,6,1,5,55.555556,2.000000,0.333333,1.666667,1.666667
42,RD Congo,4,3,1,1,1,4,3,1,44.444444,1.333333,1.000000,1.333333,0.333333
43,Uzbequistão,0,3,0,0,3,2,11,-9,0.000000,0.666667,3.666667,0.000000,-3.000000
44,Inglaterra,7,3,2,1,0,6,2,4,77.777778,2.000000,0.666667,2.333333,1.333333
45,Croácia,6,3,2,0,1,5,5,0,66.666667,1.666667,1.666667,2.000000,0.000000
46,Gana,4,3,1,1,1,2,2,0,44.444444,0.666667,0.666667,1.333333,0.000000
47,Panamá,0,3,0,0,3,0,4,-4,0.000000,0.000000,1.333333,0.000000,-1.333333

In [ ]:
print("4. Comparações")

4. Comparações

In [ ]:
print("Quem venceu mais também marcou mais gols?")
df.sort_values(["VIT", "GM"], ascending=False)[["Equipes", "VIT", "GM"]].style.hide(axis="index")

Quem venceu mais também marcou mais gols?

In [ ]:
print("Correlação entre saldo de gols e pontos")
df[["SG", "Pts"]].corr().style.hide(axis="index")

Correlação entre saldo de gols e pontos

In [ ]:
print("Média de gols das 10 melhores equipes")
top10 = df.nlargest(10, "Pts")
melhores = top10["GM"].mean()
print(melhores)

Média de gols das 10 melhores equipes
6.9

In [ ]:
print("5. Estatísticas gerais")

5. Estatísticas gerais

In [ ]:
print("Total de gols")
gols = df["GM"].sum()
print(gols)

Total de gols
215

In [ ]:
print("Média de gols")
Mgols = df["GM"].mean()
print(Mgols)

Média de gols
4.479166666666667

In [ ]:
print("Média de pontos")
pontos = df["Pts"].mean()
print(pontos)

Média de pontos
4.083333333333333

In [ ]:
print("Média de vitórias")
vitorias = df["VIT"].mean()
print(vitorias)

Média de vitórias
1.0833333333333333

In [ ]:
print("Média de empates")
empates = df["E"].mean()
print(empates)

Média de empates
0.8333333333333334

In [ ]:
print("Média de derrotas")
derrotas = df["DER"].mean()
print(derrotas)

Média de derrotas
1.0833333333333333

In [ ]:
print("Desvio padrão dos gols marcados")
df["GM"].std()

Desvio padrão dos gols marcados

2.7131639952734568

In [ ]:
print("6. Rankings")

6. Rankings

In [ ]:
print("Top 10 ataques")
df.nlargest(10, "GM")[["Equipes", "GM"]].style.hide(axis="index")

Top 10 ataques

In [ ]:
print("Top 10 defesas")
df.nsmallest(10, "GC")[["Equipes", "GC"]].style.hide(axis="index")

Top 10 defesas

In [ ]:
print("Top 10 saldos")
df.nlargest(10, "SG")[["Equipes", "SG"]].style.hide(axis="index")

Top 10 saldos

In [ ]:
print("Top 10 vitórias")
df.nlargest(10, "VIT")[["Equipes", "VIT"]].style.hide(axis="index")

Top 10 vitórias